delete.php: Fix "ArgumentCountError: Too few arguments to function error()"
Follow-up to 1e651410ca4aa3894f76c22ae7f956cabad0fa50.
This one should also have remained as `die()`, since it's
just an early return, not an error message.